**조건에 맞는 데이터 추출**

- 데이터 생성

In [1]:
import pandas as pd
df = pd.DataFrame({'a':[i for i in range(1,11)], 'b':[i for i in range(11,21)],'c':[i for i in range(21,31)]})

In [2]:
df

    a   b   c
0   1  11  21
1   2  12  22
2   3  13  23
3   4  14  24
4   5  15  25
5   6  16  26
6   7  17  27
7   8  18  28
8   9  19  29
9  10  20  30

- 문제: a와 c열을 출력하시오.

In [3]:
df[['a','c']]

    a   c
0   1  21
1   2  22
2   3  23
3   4  24
4   5  25
5   6  26
6   7  27
7   8  28
8   9  29
9  10  30

- 문제: a가 3 이상인 데이터를 출력하시오.

In [4]:
# 데이터프레임[df의 a가 3보다 큰것]
df[df['a']>=3]

    a   b   c
2   3  13  23
3   4  14  24
4   5  15  25
5   6  16  26
6   7  17  27
7   8  18  28
8   9  19  29
9  10  20  30

- 문제: a가 3 이상인 데이터 중 a,c열만 출력하시오.

In [5]:
df[df['a']>=3][['a','c']]

    a   c
2   3  23
3   4  24
4   5  25
5   6  26
6   7  27
7   8  28
8   9  29
9  10  30

- 문제: a가 3 이상이고, b가 16 미만인 데이터를 출력하시오.

In [7]:
df

    a   b   c
0   1  11  21
1   2  12  22
2   3  13  23
3   4  14  24
4   5  15  25
5   6  16  26
6   7  17  27
7   8  18  28
8   9  19  29
9  10  20  30

In [9]:
df[(df['a']>=3) & (df['b']<16)]

   a   b   c
2  3  13  23
3  4  14  24
4  5  15  25

In [10]:
# 조건으로 시리즈 만들기
a = (df['a']>=3) & (df['b']<16)

In [11]:
a

0    False
1    False
2     True
3     True
4     True
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [12]:
df[a]

   a   b   c
2  3  13  23
3  4  14  24
4  5  15  25

- 문제: a가 3이하 이거나 7이상인 데이터를 추출하시오.

In [13]:
df

    a   b   c
0   1  11  21
1   2  12  22
2   3  13  23
3   4  14  24
4   5  15  25
5   6  16  26
6   7  17  27
7   8  18  28
8   9  19  29
9  10  20  30

In [15]:
df[(df['a']<=3) | (df['a']>=7)]

    a   b   c
0   1  11  21
1   2  12  22
2   3  13  23
6   7  17  27
7   8  18  28
8   9  19  29
9  10  20  30

- 문제: a가 3 이상이고, b가 16미만이거나 c가 30인 데이터를 출력하시오.

In [16]:
df

    a   b   c
0   1  11  21
1   2  12  22
2   3  13  23
3   4  14  24
4   5  15  25
5   6  16  26
6   7  17  27
7   8  18  28
8   9  19  29
9  10  20  30

In [17]:
# 큰 조건이 30 이상임, 작은 조건은 괄호 2번침
df[(df['a']>=3) & ((df['b']<16) | (df['c'] == 30))]

    a   b   c
2   3  13  23
3   4  14  24
4   5  15  25
9  10  20  30